require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/Documentation:
  Enabled: false

Rails/Output:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 256
